site_name: "Meu SUS Digital"
site_url: "https://requisitos-de-software.github.io/2024.2-MeuSUSDigital/"
theme:
  name: "material"
 
nav:

  - Home: index.md
  - Apresentação:
    - Apresentação 01: apresentacao/apresentacao01.md
  - Atas:
    - Ata 01: atas/ata01.md
  - Pré-Rastreabilidade:
    - Rich Picture: pre-rastreabilidade/rich-picture.md
  - Planejamento:
    - Aplicativos Avaliados: planejamento/apps-avaliados.md
    - Aplicativo Selecionado: planejamento/app-selecionado.md
    - Cronograma de Planejamento: planejamento/cronograma-planejamento.md
    - Cronograma de Execução: planejamento/cronograma-execucao.md
    - Ferramentas: planejamento/ferramentas.md
    - HeatMap: planejamento/heatmap.md
    - Termo de Uso: planejamento/termo-de-uso.md
  - Verificação:
      - Visão Geral: verificacao/lista-verificacao.md
      - Grupo 4:
        - Entrega 1:
            - Planejamento da Verificação da Entrega 1: verificacao/grupo4/entrega1/entrega1.md
            - Rich Picture: verificacao/grupo4/entrega1/entrega1-1.md
      - Grupo 5:
          - Entrega 1:
              - Verificação grupo 5: verificacao/grupo5/entrega1/entrega1g5.md
    
  


