site_name: "Grupo 4"
site_url: "https://requisitos-de-software.github.io/2024.2-Grupo04/"
theme:
  name: "material"


nav:
  - Home: index.md
  - Atas:
    - Ata 01: atas/ata01.md
    - Ata 02: atas/ata02.md
  - Planejamento: 
    - Aplicativo selecionado: planejamento/apps-avaliados.md
    - Ferramentas: planejamento/ferramentas.md
    - HeatMap: planejamento/heatmap.md
    - Cronograma de Planejamento: planejamento/cronograma-planejamento.md
    - Cronograma de Execução: planejamento/cronograma-execucao.md
  - Lista de Verificação: verificacao/lista_ver.md
  